FROM node:alpine as builder 
WORKDIR '/app' 
COPY ./package*.json ./ 
RUN npm install
COPY . . 
RUN npm run build 

FROM nginx 
EXPOSE 80 
RUN ls 
RUN pwd 
COPY ./default.conf /etc/nginx/conf.d/default.conf 
COPY --from=builder /app/build /usr/share/nginx/html 

